// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD140mSlLdtHshgG98uToLEBF3kUrpKH9M',
    appId: '1:617965212599:web:6826c67b73db2ad7220e32',
    messagingSenderId: '617965212599',
    projectId: 'rete-241bc',
    authDomain: 'rete-241bc.firebaseapp.com',
    storageBucket: 'rete-241bc.firebasestorage.app',
    measurementId: 'G-H0P4WXVCFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrB2WF5JHg_Ns6hmDW-0_iNfTC0Az_DRE',
    appId: '1:617965212599:android:c17d08f60e43320d220e32',
    messagingSenderId: '617965212599',
    projectId: 'rete-241bc',
    storageBucket: 'rete-241bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8nJooke5teEuGh11nABTi7XCbe60BrR4',
    appId: '1:617965212599:ios:2d8f60c0d2f585f2220e32',
    messagingSenderId: '617965212599',
    projectId: 'rete-241bc',
    storageBucket: 'rete-241bc.firebasestorage.app',
    iosBundleId: 'com.example.retentio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD140mSlLdtHshgG98uToLEBF3kUrpKH9M',
    appId: '1:617965212599:web:0846ecd3d9e2aecc220e32',
    messagingSenderId: '617965212599',
    projectId: 'rete-241bc',
    authDomain: 'rete-241bc.firebaseapp.com',
    storageBucket: 'rete-241bc.firebasestorage.app',
    measurementId: 'G-ZGXNHP4FKE',
  );
}
